# vim: set et sw=4 ts=4 sts=4:
# Reference: https://github.com/i3/i3/blob/next/etc/config

start-at-login = true

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Run Sketchybar together with AeroSpace
# sketchbar has a built-in detection of already running process,
# so it won't be run twice on AeroSpace restart
after-startup-command = ['exec-and-forget sketchybar', 'layout h_accordion']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

[workspace-to-monitor-force-assignment]
    1 = 1
    2 = 1
    3 = 1
    4 = 1
    5 = 1
    6 = 2
    7 = 2
    8 = 2
    9 = 2
    10 = 2
    11 = 3
    12 = 3

#FIXME: This really doesn't do what I want - it fixes my bindings on the built-in
# keyboard, but breaks them on my external keyboard.
#[key-mapping]
#    preset = 'dvorak'

[mode.main.binding]
    # See: https://nikitabobko.github.io/AeroSpace/goodies#open-a-new-window-with-applescript
    #FIXME: This still doesn't work as expected. I don't want it to switch to an open Ghostty
    # window first, just open a new one on the current desktop.
    cmd-enter = '''exec-and-forget osascript -e '
    tell application "Ghostty"
        if it is running then
            activate
            tell application "System Events"
                tell process "Ghostty"
                    tell menu bar 1
                        tell menu bar item "File"
                            tell menu "File"
                                click menu item "New Window"
                            end tell
                        end tell
                    end tell
                end tell
            end tell
        else
            activate
        end if
    end tell'
    '''

    # i3 wraps focus by default
    cmd-h = 'focus left'
    cmd-t = 'focus down'
    cmd-n = 'focus up'
    cmd-s = 'focus right'
    cmd-o = 'focus left'
    cmd-u = 'focus right'
    cmd-left  = 'focus left'
    cmd-down  = 'focus down'
    cmd-up    = 'focus up'
    cmd-right = 'focus right'

    cmd-shift-h = 'move left'
    cmd-shift-t = 'move down'
    cmd-shift-n = 'move up'
    cmd-shift-s = 'move right'
    cmd-shift-o = 'move left'
    cmd-shift-u = 'move right'
    cmd-shift-left  = 'move left'
    cmd-shift-down  = 'move down'
    cmd-shift-up    = 'move up'
    cmd-shift-right = 'move right'

    # Consider using 'join-with' command as a 'split' replacement if you want to enable
    # normalizations
    #cmd-shift-v = 'split horizontal'
    #cmd-v = 'split vertical'

    cmd-f = 'fullscreen'

    #cmd-s = 'layout v_accordion' # 'layout stacking' in i3
    cmd-w = 'layout h_accordion' # 'layout tabbed' in i3
    #cmd-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

    cmd-shift-space = 'layout floating tiling' # 'floating toggle' in i3

    # Not supported, because this command is redundant in AeroSpace mental model.
    # See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
    #cmd-space = 'focus toggle_tiling_floating'

    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'
    cmd-6 = 'workspace 6'
    cmd-7 = 'workspace 7'
    cmd-8 = 'workspace 8'
    cmd-9 = 'workspace 9'
    cmd-0 = 'workspace 10'
    cmd-leftSquareBracket = 'workspace 11'
    cmd-rightSquareBracket = 'workspace 12'

    cmd-shift-1 = 'move-node-to-workspace 1'
    cmd-shift-2 = 'move-node-to-workspace 2'
    cmd-shift-3 = 'move-node-to-workspace 3'
    cmd-shift-4 = 'move-node-to-workspace 4'
    cmd-shift-5 = 'move-node-to-workspace 5'
    cmd-shift-6 = 'move-node-to-workspace 6'
    cmd-shift-7 = 'move-node-to-workspace 7'
    cmd-shift-8 = 'move-node-to-workspace 8'
    cmd-shift-9 = 'move-node-to-workspace 9'
    cmd-shift-0 = 'move-node-to-workspace 10'
    cmd-shift-leftSquareBracket = 'move-node-to-workspace 11'
    cmd-shift-rightSquareBracket = 'move-node-to-workspace 12'

    cmd-shift-c = 'reload-config'

    cmd-l = '''exec-and-forget osascript -e 'open /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app'
    '''

    cmd-a = 'mode action'
    cmd-r = 'mode resize'

[mode.action.binding]
    c = 'reload-config'
    #s = 'exec-and-forget screencapture -p'
    enter = 'mode main'
    esc = 'mode main'

[mode.resize.binding]
    h = 'resize width -50'
    t = 'resize height +50'
    n = 'resize height -50'
    s = 'resize width +50'
    left  = 'resize width -50'
    down  = 'resize height +50'
    up    = 'resize height -50'
    right = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'
