config:
  backup: true
  create: true
  dotpath: dotfiles
  minversion: 1.9.0
dotfiles:
  d_alacritty:
    dst: ~/.config/alacritty
    src: config/alacritty
  d_systemd:
    dst: ~/.config/systemd
    src: config/systemd
  f_01-native-wayland.conf:
    dst: ~/.config/environment.d/01-native-wayland.conf
    src: config/environment.d/01-native-wayland.conf
  f_nth:
    dst: ~/bin/nth
    link: absolute
    src: bin/nth
  f_lkj:
    dst: ~/bin/lkj
    link: absolute
    src: bin/lkj
  f_barrier.conf:
    dst: ~/.local/share/barrier/.barrier.conf
    src: local/share/barrier/.barrier.conf
  f_blueman-applet@.service:
    dst: ~/.config/systemd/user/blueman-applet@.service
    src: config/systemd/user/blueman-applet@.service
  f_bobthefish_colors.fish:
    dst: ~/.config/fish/functions/bobthefish_colors.fish
    src: config/fish/functions/bobthefish_colors.fish
  f_chunkwmrc:
    dst: ~/.chunkwmrc
    src: chunkwmrc
  f_i3pystatus_config.py:
    dst: ~/.config/i3pystatus/config.py
    src: config/i3pystatus/config.py
  f_diffconflicts:
    dst: ~/bin/diffconflicts
    src: bin/diffconflicts
  f_dotdrop:
    dst: ~/bin/dotdrop
    src: bin/dotdrop
  f_dpms-lock:
    dst: ~/bin/dpms-lock
    src: bin/dpms-lock
  f_extend.xprofile:
    dst: ~/.extend.xprofile
    src: extend.xprofile
  f_extend.xresources:
    dst: ~/.extend.Xresources
    src: extend.Xresources
  f_filetype.vim:
    dst: ~/.config/nvim/filetype.vim
    src: config/nvim/filetype.vim
  f_vim_filetype.vim:
    dst: ~/.vim/filetype.vim
    src: config/nvim/filetype.vim
  f_fish_plugins:
    dst: ~/.config/fish/fish_plugins
    src: config/fish/fish_plugins
  f_fish_user_key_bindings.fish:
    dst: ~/.config/fish/functions/fish_user_key_bindings.fish
    src: config/fish/functions/fish_user_key_bindings.fish
  f_flake8:
    dst: ~/.config/flake8
    src: config/flake8
  f_fonts.conf:
    dst: ~/.config/fontconfig/fonts.conf
    src: config/fontconfig/fonts.conf
  f_fqvim:
    dst: ~/bin/fqvim
    src: bin/fqvim
  f_ginit.vim:
    dst: ~/.config/nvim/ginit.vim
    src: config/nvim/ginit.vim
  f_git-diffcommit:
    dst: ~/bin/git-diffcommit
    src: bin/git-diffcommit
  f_git-glog:
    dst: ~/bin/git-glog
    src: bin/git-glog
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_gopath.fish:
    dst: ~/.config/fish/functions/gopath.fish
    src: config/fish/functions/gopath.fish
  f_hyper.js:
    dst: ~/.hyper.js
    src: hyper.js
  f_i3-randr-update:
    dst: ~/bin/i3-randr-update
    src: bin/i3-randr-update
  f_i3_config:
    dst: ~/.config/i3/config
    src: config/i3/config
  f_i3blocks_config:
    dst: ~/.config/i3blocks/config
    src: config/i3blocks/config
  f_i3exit:
    dst: ~/bin/i3exit
    src: bin/i3exit
  f_init.vim:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_vimrc:
    dst: ~/.vimrc
    src: config/nvim/init.vim
  f_kdeconnect-indicator@.service:
    dst: ~/.config/systemd/user/kdeconnect-indicator@.service
    src: config/systemd/user/kdeconnect-indicator@.service
  f_khdrc:
    dst: ~/.khdrc
    src: khdrc
  f_kitty.conf:
    dst: ~/.config/kitty/kitty.conf
    src: config/kitty/kitty.conf
  f_l.fish:
    dst: ~/.config/fish/functions/l.fish
    src: config/fish/functions/l.fish
  f_la.fish:
    dst: ~/.config/fish/functions/la.fish
    src: config/fish/functions/la.fish
  f_lal.fish:
    dst: ~/.config/fish/functions/lal.fish
    src: config/fish/functions/lal.fish
  f_launch-terminal:
    dst: ~/bin/launch-terminal
    src: bin/launch-terminal
  f_line-diff:
    dst: ~/bin/line-diff
    link: absolute
    src: bin/sabdc
  f_ll.fish:
    dst: ~/.config/fish/functions/ll.fish
    src: config/fish/functions/ll.fish
  f_mako@.service:
    dst: ~/.config/systemd/user/mako@.service
    src: config/systemd/user/mako@.service
  f_notify-volume:
    dst: ~/bin/notify-volume
    src: bin/notify-volume
  f_npmrc:
    dst: ~/.npmrc
    src: npmrc
  f_psqlrc:
    dst: ~/.psqlrc
    src: psqlrc
  f_pyg:
    dst: ~/bin/pyg
    src: bin/pyg
  f_pygments-styles:
    dst: ~/bin/pygments-styles
    src: bin/pygments-styles
  f_pylintrc:
    dst: ~/.pylintrc
    src: pylintrc
  f_qvim:
    dst: ~/bin/qvim
    src: bin/qvim
  f_rc.xsh:
    dst: ~/.config/xonsh/rc.xsh
    src: config/xonsh/rc.xsh
  f_rgbcolors:
    dst: ~/bin/rgbcolors
    src: bin/rgbcolors
  f_rofi_config:
    dst: ~/.config/rofi/config.rasi
    src: config/rofi/config.rasi
  f_sabdc:
    dst: ~/bin/sabdc
    link: absolute
    src: bin/sabdc
  f_stalonetray@.service:
    dst: ~/.config/systemd/user/stalonetray@.service
    src: config/systemd/user/stalonetray@.service
  f_start-sway.fish:
    dst: ~/.config/fish/conf.d/start-sway.fish
    src: config/fish/conf.d/start-sway.fish
  f_startsway.fish:
    dst: ~/.config/fish/functions/startsway.fish
    src: config/fish/functions/startsway.fish
  f_sterminalrc:
    dst: ~/.sterminalrc
    src: sterminalrc
  f_sway_config:
    dst: ~/.config/sway/config
    src: config/sway/config
  f_synergy.conf:
    dst: ~/.synergy.conf
    src: synergy.conf
  f_t.fish:
    dst: ~/.config/fish/functions/t.fish
    src: config/fish/functions/t.fish
  f_theme.rasi:
    dst: ~/.config/rofi/theme.rasi
    src: config/rofi/theme.rasi
  f_tl.fish:
    dst: ~/.config/fish/functions/tl.fish
    src: config/fish/functions/tl.fish
  f_toggle-inputdev:
    dst: ~/bin/toggle-inputdev
    src: bin/toggle-inputdev
  f_toggle-systray:
    dst: ~/bin/toggle-systray
    src: bin/toggle-systray
  f_toggle-touchpad:
    dst: ~/bin/toggle-touchpad
    src: bin/toggle-touchpad
  f_toggle-touchscreen:
    dst: ~/bin/toggle-touchscreen
    src: bin/toggle-touchscreen
  f_trayer@.service:
    dst: ~/.config/systemd/user/trayer@.service
    src: config/systemd/user/trayer@.service
  f_tree.fish:
    dst: ~/.config/fish/functions/tree.fish
    src: config/fish/functions/tree.fish
  f_urlquote:
    dst: ~/bin/urlquote
    src: bin/urlquote
  f_vars.fish:
    dst: ~/.config/fish/conf.d/vars.fish
    src: config/fish/conf.d/vars.fish
  f_word-diff:
    dst: ~/bin/word-diff
    link: absolute
    src: bin/sabdc
  f_xcffibaer@.service:
    dst: ~/.config/systemd/user/xcffibaer@.service
    src: config/systemd/user/xcffibaer@.service
  f_fixterm:
    src: bin/fixterm
    dst: ~/bin/fixterm
    chmod: '755'
  f_index.theme:
    src: icons/default/index.theme
    dst: ~/.icons/default/index.theme
  f_settings.ini:
    src: config/gtk-3.0/settings.ini
    dst: ~/.config/gtk-3.0/settings.ini
  f_gtk-4.0_settings.ini:
    src: config/gtk-4.0/settings.ini
    dst: ~/.config/gtk-4.0/settings.ini
  f_rofi-lpass-run:
    src: bin/rofi-lpass-run
    dst: ~/bin/rofi-lpass-run
    chmod: '755'
  f_compare-dotfiles:
    src: bin/compare-dotfiles
    dst: ~/bin/compare-dotfiles
    chmod: '755'
  f_with-us-keyboard:
    src: bin/with-us-keyboard
    dst: ~/bin/with-us-keyboard
    chmod: '755'
  f_rofi-run:
    src: bin/rofi-run
    dst: ~/bin/rofi-run
    chmod: '755'
  f_swayexit:
    src: bin/swayexit
    dst: ~/bin/swayexit
    chmod: '755'
  f_sway-help:
    src: bin/sway-help
    dst: ~/bin/sway-help
    chmod: '755'
  f_foot.ini:
    src: config/foot/foot.ini
    dst: ~/.config/foot/foot.ini
  f_config:
    src: config/waybar/config
    dst: ~/.config/waybar/config
  f_style.css:
    src: config/waybar/style.css
    dst: ~/.config/waybar/style.css
  f_xdg-desktop-portal-wlr_config:
    src: config/xdg-desktop-portal-wlr/config
    dst: ~/.config/xdg-desktop-portal-wlr/config
  d_waybar_scripts:
    src: config/waybar/scripts
    dst: ~/.config/waybar/scripts
  d_sway_scripts:
    src: config/sway/scripts
    dst: ~/.config/sway/scripts
  f_monitor-ping-drops:
    src: bin/monitor-ping-drops
    dst: ~/bin/monitor-ping-drops
    chmod: '755'
  f_newbranch.fish:
    src: config/fish/functions/newbranch.fish
    dst: ~/.config/fish/functions/newbranch.fish
  f_newcommit.fish:
    src: config/fish/functions/newcommit.fish
    dst: ~/.config/fish/functions/newcommit.fish
  f_startsway:
    src: bin/startsway
    dst: ~/bin/startsway
    chmod: '755'
profiles:
  azrahn:
    dotfiles:
    - f_vimrc
    - f_vim_filetype.vim
    - f_init.vim
    - f_ginit.vim
    - f_filetype.vim
    - f_i3_config
    - f_i3pystatus_config.py
    - f_fish_plugins
    - f_fish_user_key_bindings.fish
    - f_vars.fish
    - f_rc.xsh
    - f_fonts.conf
    - f_hyper.js
    - f_extend.xprofile
    - f_extend.xresources
    - f_synergy.conf
    - f_gitconfig
    - f_sterminalrc
    - f_npmrc
    - d_systemd
    - d_alacritty
    - f_dpms-lock
    - f_dotdrop
    - f_git-diffcommit
    - f_git-glog
    - f_diffconflicts
    - f_nth
    - f_lkj
    - f_sabdc
    - f_word-diff
    - f_line-diff
    - f_i3-randr-update
    - f_i3exit
    - f_launch-terminal
    - f_notify-volume
    - f_pyg
    - f_pygments-styles
    - f_qvim
    - f_fqvim
    - f_toggle-touchpad
    - f_toggle-inputdev
    - f_urlquote
    - f_flake8
    - f_pylintrc
    - f_kitty.conf
    - f_bobthefish_colors.fish
    - f_rgbcolors
    - f_xcffibaer@.service
    - f_stalonetray@.service
    - f_tree.fish
    - f_l.fish
    - f_la.fish
    - f_lal.fish
    - f_ll.fish
    - f_t.fish
    - f_tl.fish
    - f_gopath.fish
    - f_rofi_config
    - f_theme.rasi
    - f_blueman-applet@.service
    - f_kdeconnect-indicator@.service
    - f_mako@.service
    - f_sway_config
    - f_i3blocks_config
    - f_01-native-wayland.conf
    - f_startsway.fish
    - f_start-sway.fish
    - f_psqlrc
    - f_barrier.conf
    - f_fixterm
    - f_index.theme
    - f_settings.ini
    - f_gtk-4.0_settings.ini
    - f_rofi-lpass-run
    - f_compare-dotfiles
    - f_with-us-keyboard
    - f_rofi-run
    - f_swayexit
    - f_sway-help
    - f_foot.ini
    - f_config
    - f_style.css
    - f_xdg-desktop-portal-wlr_config
    - d_waybar_scripts
    - d_sway_scripts
    - f_monitor-ping-drops
  prototype:
    dotfiles:
    - f_vimrc
    - f_vim_filetype.vim
    - f_init.vim
    - f_ginit.vim
    - f_filetype.vim
    - f_i3_config
    - f_i3pystatus_config.py
    - f_fish_plugins
    - f_fish_user_key_bindings.fish
    - f_vars.fish
    - f_rc.xsh
    - f_fonts.conf
    - f_hyper.js
    - f_extend.xprofile
    - f_extend.xresources
    - f_synergy.conf
    - f_gitconfig
    - f_sterminalrc
    - f_npmrc
    - d_systemd
    - d_alacritty
    - f_dpms-lock
    - f_dotdrop
    - f_git-diffcommit
    - f_git-glog
    - f_diffconflicts
    - f_nth
    - f_lkj
    - f_sabdc
    - f_word-diff
    - f_line-diff
    - f_i3-randr-update
    - f_i3exit
    - f_launch-terminal
    - f_notify-volume
    - f_pyg
    - f_pygments-styles
    - f_qvim
    - f_fqvim
    - f_toggle-touchpad
    - f_toggle-inputdev
    - f_toggle-touchscreen
    - f_urlquote
    - f_flake8
    - f_pylintrc
    - f_kitty.conf
    - f_bobthefish_colors.fish
    - f_rgbcolors
    - f_xcffibaer@.service
    - f_toggle-systray
    - f_trayer@.service
    - f_stalonetray@.service
    - f_tree.fish
    - f_l.fish
    - f_la.fish
    - f_lal.fish
    - f_ll.fish
    - f_t.fish
    - f_tl.fish
    - f_gopath.fish
    - f_rofi_config
    - f_theme.rasi
    - f_blueman-applet@.service
    - f_kdeconnect-indicator@.service
    - f_mako@.service
    - f_sway_config
    - f_i3blocks_config
    - f_01-native-wayland.conf
    - f_startsway.fish
    - f_start-sway.fish
    - f_psqlrc
    - f_barrier.conf
    - f_fixterm
    - f_index.theme
    - f_settings.ini
    - f_gtk-4.0_settings.ini
    - f_rofi-lpass-run
    - f_compare-dotfiles
    - f_with-us-keyboard
    - f_rofi-run
    - f_swayexit
    - f_sway-help
    - f_foot.ini
    - f_config
    - f_style.css
    - f_xdg-desktop-portal-wlr_config
    - d_waybar_scripts
    - d_sway_scripts
  syl:
    dotfiles:
    - f_vimrc
    - f_vim_filetype.vim
    - f_init.vim
    - f_ginit.vim
    - f_filetype.vim
    - f_i3_config
    - f_i3pystatus_config.py
    - f_fish_plugins
    - f_fish_user_key_bindings.fish
    - f_vars.fish
    - f_rc.xsh
    - f_fonts.conf
    - f_hyper.js
    - f_extend.xprofile
    - f_extend.xresources
    - f_synergy.conf
    - f_gitconfig
    - f_sterminalrc
    - f_npmrc
    - d_systemd
    - d_alacritty
    - f_dpms-lock
    - f_dotdrop
    - f_git-diffcommit
    - f_git-glog
    - f_diffconflicts
    - f_nth
    - f_lkj
    - f_sabdc
    - f_word-diff
    - f_line-diff
    - f_i3-randr-update
    - f_i3exit
    - f_launch-terminal
    - f_notify-volume
    - f_pyg
    - f_pygments-styles
    - f_qvim
    - f_fqvim
    - f_toggle-touchpad
    - f_toggle-inputdev
    - f_urlquote
    - f_flake8
    - f_pylintrc
    - f_kitty.conf
    - f_bobthefish_colors.fish
    - f_rgbcolors
    - f_xcffibaer@.service
    - f_stalonetray@.service
    - f_tree.fish
    - f_l.fish
    - f_la.fish
    - f_lal.fish
    - f_ll.fish
    - f_t.fish
    - f_tl.fish
    - f_gopath.fish
    - f_rofi_config
    - f_theme.rasi
    - f_blueman-applet@.service
    - f_kdeconnect-indicator@.service
    - f_mako@.service
    - f_sway_config
    - f_i3blocks_config
    - f_01-native-wayland.conf
    - f_startsway.fish
    - f_start-sway.fish
    - f_psqlrc
    - f_barrier.conf
    - f_fixterm
    - f_index.theme
    - f_settings.ini
    - f_gtk-4.0_settings.ini
    - f_rofi-lpass-run
    - f_compare-dotfiles
    - f_with-us-keyboard
    - f_rofi-run
    - f_swayexit
    - f_sway-help
    - f_foot.ini
    - f_config
    - f_style.css
    - f_xdg-desktop-portal-wlr_config
    - d_waybar_scripts
    - d_sway_scripts
  tiny:
    dotfiles:
    - f_vimrc
    - f_vim_filetype.vim
    - f_init.vim
    - f_ginit.vim
    - f_filetype.vim
    - f_i3_config
    - f_i3pystatus_config.py
    - f_fish_plugins
    - f_fish_user_key_bindings.fish
    - f_vars.fish
    - f_rc.xsh
    - f_fonts.conf
    - f_hyper.js
    - f_extend.xprofile
    - f_extend.xresources
    - f_synergy.conf
    - f_gitconfig
    - f_sterminalrc
    - f_npmrc
    - d_systemd
    - d_alacritty
    - f_dpms-lock
    - f_dotdrop
    - f_git-diffcommit
    - f_git-glog
    - f_diffconflicts
    - f_nth
    - f_lkj
    - f_sabdc
    - f_word-diff
    - f_line-diff
    - f_i3-randr-update
    - f_i3exit
    - f_launch-terminal
    - f_notify-volume
    - f_pyg
    - f_pygments-styles
    - f_qvim
    - f_fqvim
    - f_toggle-touchpad
    - f_toggle-inputdev
    - f_toggle-touchscreen
    - f_urlquote
    - f_flake8
    - f_pylintrc
    - f_kitty.conf
    - f_bobthefish_colors.fish
    - f_rgbcolors
    - f_xcffibaer@.service
    - f_stalonetray@.service
    - f_tree.fish
    - f_l.fish
    - f_la.fish
    - f_lal.fish
    - f_ll.fish
    - f_t.fish
    - f_tl.fish
    - f_gopath.fish
    - f_rofi_config
    - f_theme.rasi
    - f_blueman-applet@.service
    - f_kdeconnect-indicator@.service
    - f_mako@.service
    - f_sway_config
    - f_i3blocks_config
    - f_01-native-wayland.conf
    - f_startsway.fish
    - f_start-sway.fish
    - f_psqlrc
    - f_barrier.conf
    - f_fixterm
    - f_index.theme
    - f_settings.ini
    - f_gtk-4.0_settings.ini
    - f_rofi-lpass-run
    - f_compare-dotfiles
    - f_with-us-keyboard
    - f_rofi-run
    - f_swayexit
    - f_sway-help
    - f_foot.ini
    - f_config
    - f_style.css
    - f_xdg-desktop-portal-wlr_config
    - d_waybar_scripts
    - d_sway_scripts
  nova:
    dotfiles:
    - f_vimrc
    - f_vim_filetype.vim
    - f_init.vim
    - f_ginit.vim
    - f_filetype.vim
    - f_i3_config
    - f_i3pystatus_config.py
    - f_fish_plugins
    - f_fish_user_key_bindings.fish
    - f_vars.fish
    - f_rc.xsh
    - f_fonts.conf
    - f_hyper.js
    - f_extend.xprofile
    - f_extend.xresources
    - f_synergy.conf
    - f_gitconfig
    - f_sterminalrc
    - f_npmrc
    - d_systemd
    - d_alacritty
    - f_dpms-lock
    - f_dotdrop
    - f_git-diffcommit
    - f_git-glog
    - f_diffconflicts
    - f_nth
    - f_lkj
    - f_sabdc
    - f_word-diff
    - f_line-diff
    - f_i3-randr-update
    - f_i3exit
    - f_launch-terminal
    - f_notify-volume
    - f_pyg
    - f_pygments-styles
    - f_qvim
    - f_fqvim
    - f_toggle-touchpad
    - f_toggle-inputdev
    - f_urlquote
    - f_flake8
    - f_pylintrc
    - f_kitty.conf
    - f_bobthefish_colors.fish
    - f_rgbcolors
    - f_xcffibaer@.service
    - f_stalonetray@.service
    - f_tree.fish
    - f_l.fish
    - f_la.fish
    - f_lal.fish
    - f_ll.fish
    - f_t.fish
    - f_tl.fish
    - f_gopath.fish
    - f_rofi_config
    - f_theme.rasi
    - f_blueman-applet@.service
    - f_kdeconnect-indicator@.service
    - f_mako@.service
    - f_sway_config
    - f_i3blocks_config
    - f_01-native-wayland.conf
    - f_startsway.fish
    - f_start-sway.fish
    - f_psqlrc
    - f_barrier.conf
    - f_fixterm
    - f_index.theme
    - f_settings.ini
    - f_gtk-4.0_settings.ini
    - f_rofi-lpass-run
    - f_compare-dotfiles
    - f_with-us-keyboard
    - f_rofi-run
    - f_swayexit
    - f_sway-help
    - f_foot.ini
    - f_config
    - f_style.css
    - f_xdg-desktop-portal-wlr_config
    - d_waybar_scripts
    - d_sway_scripts
    - f_newbranch.fish
    - f_newcommit.fish
    - f_startsway
